# Generated by Django 6.0.6 on 2026-06-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(default='higher', max_length=10)),
                ('low', models.FloatField()),
                ('medium', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Umbral',
                'verbose_name_plural': 'Configuraciones de Umbrales',
                'db_table': 'umbral_config',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('mensaje', models.TextField()),
                ('id_equipo_monitoreo', models.ForeignKey(blank=True, db_column='id_equipo_monitoreo', null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.equipomonitoreo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
    ]
