# Generated by Django 6.0.6 on 2026-06-20 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('buildings', '0002_alter_building_address_alter_building_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLimitConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=50)),
                ('max_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_limits', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Límite de Sensor',
                'verbose_name_plural': 'Límites de Sensores',
                'db_table': 'limite_sensor_config',
                'unique_together': {('building', 'variable')},
            },
        ),
    ]
