# Generated by Django 6.0.6 on 2026-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
