import logging
import threading
import time
from typing import Any, Dict, List, Optional, Set

from apps.sensors.simulation.models import BuildingSimulator
from apps.sensors.simulation.constants import PROTECTION_HOLD_SECONDS
from apps.sensors.sensor_config import PUMP_VARS, ELEVATOR_VARS
from apps.alerts.services.alert_service import send_email_alert, persist_notification_in_django
from .utils import (
    COOLDOWN_SECONDS, get_attribute, set_attribute, translate_device_to_spanish,
)

logger = logging.getLogger(__name__)


def _build_protection_notification_payload(
    reason: Optional[str], targets_text_es: str
) -> Dict[str, Any]:
    return {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "variable": "auto_protection",
        "value": targets_text_es,
        "risk": "Critical",
        "message": f"Automatic protection activated{(' (' + reason + ')') if reason else ''}. Forced operation / Safe state: {targets_text_es}.",
    }


def _send_protection_email(
    reason: Optional[str],
    targets_text_es: str,
    targets_text_raw: str,
    last_email_time: float,
) -> float:
    now_ts = time.time()
    if now_ts - last_email_time <= COOLDOWN_SECONDS:
        return last_email_time
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    subject = f"[Protection activated] Forced operation: {targets_text_es}"
    body = (
        f"AUTOMATIC PROTECTION REPORT\n\n"
        f"The automatic protection system has detected a critical condition "
        f"and activated forced operation / safe state for the following devices.\n\n"
        f"EVENT DETAILS:\n"
        f"{'':->44}\n"
        f"Date/Time:      {timestamp}\n"
        f"Devices:        {targets_text_es}\n"
        f"Reason:         {reason or 'critical condition detected'}\n"
        f"Status:         protection activated\n\n"
        f"SUGGESTED CORRECTIVE MEASURES:\n"
        f"{'':->44}\n"
        f"Action: Inspect the indicated devices before resuming operation. "
        f"Devices will automatically restore after the protection period.\n\n"
        f"This is a contingency message automatically generated by the protection module."
    )
    threading.Thread(
        target=send_email_alert, args=("Critical", subject, body), daemon=True
    ).start()
    return now_ts


def enter_protection_mode(
    reason: Optional[str] = None,
    targets: Optional[Set[str]] = None,
    sim: Optional[BuildingSimulator] = None,
) -> None:
    if not targets:
        logger.warning("Protection requested without targets; nothing will be done.")
        return

    pe = get_attribute(sim, "protection_ends")
    pn = get_attribute(sim, "pending_notifications")
    les = get_attribute(sim, "last_email_sent_time")

    now = time.time()
    for device in targets:
        pe[device] = now + PROTECTION_HOLD_SECONDS

    reason_text = f" ({reason})" if reason else ""
    targets_text_es = " and ".join(translate_device_to_spanish(d) for d in sorted(targets))
    targets_text_raw = " and ".join(sorted(targets))
    logger.warning("PROTECTION ACTIVATED%s. Forced operation: %s.", reason_text, targets_text_raw)

    notification_payload = _build_protection_notification_payload(reason, targets_text_es)
    pn.append(notification_payload)

    alert_enabled = sim.alert_enabled if sim else True
    if alert_enabled:
        eid = sim.edificio_id if sim else None
        persist_notification_in_django(
            "auto_protection", targets_text_es, "Critical",
            notification_payload["message"], edificio_id=eid
        )

    new_les = _send_protection_email(reason, targets_text_es, targets_text_raw, les)
    set_attribute(sim, "last_email_sent_time", new_les)


def _get_expired_devices(protection_ends_dict: dict[str, float]) -> list[str]:
    now = time.time()
    return [d for d, end in protection_ends_dict.items() if end and now >= end]


def _reset_device(device: str, sim: Optional[BuildingSimulator]) -> None:
    from apps.sensors.simulation.controls import reset_critical_values

    try:
        reset_critical_values({device}, sim)
    except Exception:
        logger.exception("Error resetting critical values for %s", device)


def _clear_device_alerts(device: str, active_alerts_dict: dict[str, str]) -> None:
    try:
        if device == "pump":
            for v in PUMP_VARS + ["rationing"]:
                active_alerts_dict.pop(v, None)
        elif device == "elevator":
            for v in ELEVATOR_VARS:
                active_alerts_dict.pop(v, None)
    except Exception:
        pass


def _notify_protection_ended(device: str, sim: Optional[BuildingSimulator], pn: list) -> None:
    device_es = "the water pump" if device == "pump" else "the elevator"
    alert_enabled = sim.alert_enabled if sim else True
    if alert_enabled:
        eid = sim.edificio_id if sim else None
        persist_notification_in_django(
            f"protection_{device}",
            None,
            "Info",
            f"Protection ended for {device_es}. Normal operation restored.",
            edificio_id=eid,
        )
    notification_payload = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "variable": f"protection_{device}",
        "value": None,
        "risk": "Info",
        "message": f"Protection ended for {device_es}. Normal operation restored.",
    }
    pn.append(notification_payload)


def update_protection_state(sim: Optional[BuildingSimulator] = None) -> None:
    pe = get_attribute(sim, "protection_ends")
    aa = get_attribute(sim, "active_alerts")
    pn = get_attribute(sim, "pending_notifications")

    expired = _get_expired_devices(pe)
    for device in expired:
        _reset_device(device, sim)
        _clear_device_alerts(device, aa)
        del pe[device]
        logger.info("Protection ended for %s. Device restored.", device)
        _notify_protection_ended(device, sim, pn)
