# Generated by Django 6.0.6 on 2026-06-10 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nb_edificio', models.CharField(max_length=255)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
            ],
            options={
                'db_table': 'edificio',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='EquipoMonitoreo',
            fields=[
                ('id_equipo_monitoreo', models.AutoField(primary_key=True, serialize=False)),
                ('nb_equipo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('bomba', 'Bomba de agua'), ('elevador', 'Elevador')], default='bomba', max_length=20)),
                ('status', models.CharField(choices=[('operativo', 'Operativo'), ('falla', 'Falla'), ('mantenimiento', 'Mantenimiento')], default='operativo', max_length=20)),
                ('id_edificio', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='front.edificio')),
            ],
            options={
                'db_table': 'equipo_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(default='US', max_length=2)),
                ('registrado', models.BooleanField(default=False)),
                ('alerts_disabled', models.BooleanField(default=False)),
                ('alerts_disabled_until', models.FloatField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='front.persona')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('mensaje', models.TextField()),
                ('id_equipo_monitoreo', models.ForeignKey(blank=True, db_column='id_equipo_monitoreo', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.equipomonitoreo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEdificio',
            fields=[
                ('id_usuario_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('id_edificio', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='front.edificio')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='front.usuario')),
            ],
            options={
                'db_table': 'usuario_edificio',
            },
        ),
    ]
