# Generated by Django 6.0.6 on 2026-06-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(default='higher', max_length=10)),
                ('low', models.FloatField()),
                ('medium', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Umbral',
                'verbose_name_plural': 'Configuraciones de Umbrales',
                'db_table': 'umbral_config',
            },
        ),
    ]
