# Generated by Django 6.0.5 on 2026-06-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='has_ascensor',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='has_bomba',
        ),
        migrations.AddField(
            model_name='equipomonitoreo',
            name='tipo',
            field=models.CharField(choices=[('bomba', 'Bomba de agua'), ('elevador', 'Elevador')], default='bomba', max_length=20),
        ),
    ]
