# Generated by Django 6.0.5 on 2026-06-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_remove_edificio_has_ascensor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiposensor',
            name='id_dispos_sensor',
        ),
        migrations.RemoveField(
            model_name='equiposensor',
            name='id_equipo_monitoreo',
        ),
        migrations.RemoveField(
            model_name='historicofalla',
            name='id_equipo_sensor',
        ),
        migrations.RemoveField(
            model_name='historicofalla',
            name='id_status_equipo_monitoreo',
        ),
        migrations.RemoveField(
            model_name='statusequipomonitoreo',
            name='id_status',
        ),
        migrations.RemoveField(
            model_name='statusequipomonitoreo',
            name='id_equipo_monitoreo',
        ),
        migrations.AddField(
            model_name='equipomonitoreo',
            name='status',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('falla', 'Falla'), ('mantenimiento', 'Mantenimiento')], default='operativo', max_length=20),
        ),
        migrations.DeleteModel(
            name='AccionPrev',
        ),
        migrations.DeleteModel(
            name='DisposSensor',
        ),
        migrations.DeleteModel(
            name='EquipoSensor',
        ),
        migrations.DeleteModel(
            name='HistoricoFalla',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='StatusEquipoMonitoreo',
        ),
    ]
