# Generated by Django 6.0.5 on 2026-06-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alerts_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='alerts_disabled_until',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
