# Generated by Django 6.0.5 on 2026-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_persona_direccion_alter_edificio_rif'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
