# Generated by Django 6.0.6 on 2026-06-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(default='US', max_length=2)),
                ('registrado', models.BooleanField(default=False)),
                ('alerts_disabled', models.BooleanField(default=False)),
                ('alerts_disabled_until', models.FloatField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='users.persona')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
