# Generated by Django 6.0.6 on 2026-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(db_column='apellido', max_length=255),
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(db_column='telefono', max_length=50),
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='registrado',
            field=models.BooleanField(db_column='registrado', default=False),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='registrado',
            new_name='registered',
        ),
    ]
