# Generated by Django 6.0.6 on 2026-06-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_alerts_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
