# Generated by Django 6.0.6 on 2026-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ci',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=75),
        ),
        migrations.AlterField(
            model_name='persona',
            name='first_last_name',
            field=models.CharField(db_column='primer_apellido', max_length=40),
        ),
        migrations.AlterField(
            model_name='persona',
            name='first_name',
            field=models.CharField(db_column='primer_nombre', max_length=40),
        ),
        migrations.AlterField(
            model_name='persona',
            name='middle_name',
            field=models.CharField(blank=True, db_column='segundo_nombre', default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='persona',
            name='second_last_name',
            field=models.CharField(blank=True, db_column='segundo_apellido', default='', max_length=40),
        ),
    ]
