# Generated by Django 6.0.6 on 2026-06-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_persona_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='phone',
        ),
    ]
