# Generated by Django 6.0.6 on 2026-06-22 03:27

from django.db import migrations, models


def set_email_alerts_disabled_true(apps, schema_editor):
    Usuario = apps.get_model('users', 'Usuario')
    Usuario.objects.update(email_alerts_disabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_email_alerts_disabled'),
    ]

    operations = [
        migrations.RunPython(set_email_alerts_disabled_true, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usuario',
            name='email_alerts_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
