# Generated by Django 6.0.6 on 2026-06-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_persona_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ci',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
