# Generated by Django 6.0.6 on 2026-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_update_email_alerts_disabled_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alerts_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
