# Generated by Django 6.0.6 on 2026-06-22 14:48

from django.db import migrations, models


def enable_email_alerts(apps, schema_editor):
    Usuario = apps.get_model("users", "Usuario")
    Usuario.objects.update(email_alerts_disabled=False)


def disable_email_alerts(apps, schema_editor):
    Usuario = apps.get_model("users", "Usuario")
    Usuario.objects.update(email_alerts_disabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usuario_alerts_cleared_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email_alerts_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(enable_email_alerts, disable_email_alerts),
    ]
