# Generated by Django 6.0.6 on 2026-06-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_enable_email_alerts_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_alerts_disabled',
        ),
    ]
