# Generated by Django 6.0.6 on 2026-06-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_email_alerts_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('US', 'Usuario'), ('SA', 'Super Administrador')], default='US', max_length=2),
        ),
    ]
