# Generated by Django 6.0.6 on 2026-06-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nb_edificio', models.CharField(max_length=255)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
            ],
            options={
                'db_table': 'edificio',
            },
        ),
        migrations.CreateModel(
            name='EquipoMonitoreo',
            fields=[
                ('id_equipo_monitoreo', models.AutoField(primary_key=True, serialize=False)),
                ('nb_equipo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('bomba', 'Bomba de agua'), ('elevador', 'Elevador')], default='bomba', max_length=20)),
                ('status', models.CharField(choices=[('operativo', 'Operativo'), ('falla', 'Falla'), ('mantenimiento', 'Mantenimiento')], default='operativo', max_length=20)),
                ('id_edificio', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='buildings.edificio')),
            ],
            options={
                'db_table': 'equipo_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEdificio',
            fields=[
                ('id_usuario_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('id_edificio', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='buildings.edificio')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'usuario_edificio',
            },
        ),
    ]
