# Generated by Django 6.0.6 on 2026-06-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringequipment',
            options={'ordering': ['equipment_type']},
        ),
    ]
