# Generated by Django 6.0.6 on 2026-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(db_column='direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(db_column='nb_edificio', max_length=40),
        ),
        migrations.AlterField(
            model_name='building',
            name='rif',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
