# Generated by Django 6.0.6 on 2026-06-29 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_monitoringequipment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floors',
            field=models.PositiveIntegerField(db_column='cantidad_pisos', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='monitoringequipment',
            constraint=models.UniqueConstraint(fields=('building', 'equipment_type'), name='uq_building_equipment_type'),
        ),
    ]
