# Generated by Django 6.0.6 on 2026-06-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_rename_models_and_fields'),
        ('users', '0002_alter_persona_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(db_column='direccion'),
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(db_column='id_edificio', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(db_column='nb_edificio', max_length=255),
        ),
        migrations.AlterField(
            model_name='monitoringequipment',
            name='building',
            field=models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='monitoringequipment',
            name='equipment_type',
            field=models.CharField(choices=[('bomba', 'Bomba de agua'), ('elevador', 'Elevador')], db_column='tipo', default='bomba', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoringequipment',
            name='id',
            field=models.AutoField(db_column='id_equipo_monitoreo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monitoringequipment',
            name='name',
            field=models.CharField(db_column='nb_equipo', max_length=255),
        ),
        migrations.AlterField(
            model_name='userbuilding',
            name='building',
            field=models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='userbuilding',
            name='id',
            field=models.AutoField(db_column='id_usuario_beneficiario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbuilding',
            name='user',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='building_assignments', to='users.usuario'),
        ),
    ]
