import os
import threading
import time
import logging
from typing import Any, Dict, List, Optional, Set

from apps.sensors.simulation.constants import (
    LOG_SIM, RATIONING_THRESHOLD, PROTECTION_HOLD_SECONDS,
)
from apps.sensors.simulation.globals import (
    sensor_data, protection_ends, active_alerts,
    pending_notifications, last_email_sent_time,
)
from apps.sensors.sensor_config import (
    VAR_NAMES, PUMP_VARS, ELEVATOR_VARS,
    RISK_NAMES_ES, DEVICE_NAMES_ES,
)
from apps.alerts.services.alert_service import (
    get_unit,
    get_building_emails,
    generate_recommendations,
    get_professional_action,
    send_email_alert,
    persist_notification_in_django,
)

logger = logging.getLogger(__name__)

SMTP_SERVER: str = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT: int = int(os.environ.get("SMTP_PORT", 587))
SMTP_USER: str = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD: str = os.environ.get("SMTP_PASSWORD", "")

COOLDOWN_SECONDS: int = 300


def _translate_device_to_spanish(device: str) -> str:
    return DEVICE_NAMES_ES.get(device, device)


def _translate_variable_to_spanish(variable: str) -> str:
    return VAR_NAMES.get(variable, variable.replace("_", " ").title())


def _get_attribute(sim: Any, attr: str) -> Any:
    if sim is not None:
        return getattr(sim, attr)
    return globals()[attr]


def _set_attribute(sim: Any, attr: str, value: Any) -> None:
    if sim is not None:
        setattr(sim, attr, value)
    else:
        globals()[attr] = value


def _build_protection_notification_payload(
    reason: Optional[str], targets_text_es: str
) -> Dict[str, Any]:
    return {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "variable": "auto_protection",
        "value": targets_text_es,
        "risk": "Critical",
        "message": f"Automatic protection activated{(' (' + reason + ')') if reason else ''}. Forced operation / Safe state: {targets_text_es}.",
    }


def _send_protection_email(
    reason: Optional[str],
    targets_text_es: str,
    targets_text_raw: str,
    last_email_time: float,
) -> float:
    now_ts = time.time()
    if now_ts - last_email_time <= COOLDOWN_SECONDS:
        return last_email_time
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    subject = f"[Protection activated] Forced operation: {targets_text_es}"
    body = (
        f"AUTOMATIC PROTECTION REPORT\n\n"
        f"The automatic protection system has detected a critical condition "
        f"and activated forced operation / safe state for the following devices.\n\n"
        f"EVENT DETAILS:\n"
        f"{'':->44}\n"
        f"Date/Time:      {timestamp}\n"
        f"Devices:        {targets_text_es}\n"
        f"Reason:         {reason or 'critical condition detected'}\n"
        f"Status:         protection activated\n\n"
        f"SUGGESTED CORRECTIVE MEASURES:\n"
        f"{'':->44}\n"
        f"Action: Inspect the indicated devices before resuming operation. "
        f"Devices will automatically restore after the protection period.\n\n"
        f"This is a contingency message automatically generated by the protection module."
    )
    threading.Thread(
        target=send_email_alert, args=("Critical", subject, body), daemon=True
    ).start()
    return now_ts


def enter_protection_mode(
    reason: Optional[str] = None,
    targets: Optional[Set[str]] = None,
    sim: Any = None,
) -> None:
    if not targets:
        logger.warning("Protection requested without targets; nothing will be done.")
        return

    pe = _get_attribute(sim, "protection_ends")
    pn = _get_attribute(sim, "pending_notifications")
    les = _get_attribute(sim, "last_email_sent_time")

    now = time.time()
    for device in targets:
        pe[device] = now + PROTECTION_HOLD_SECONDS

    reason_text = f" ({reason})" if reason else ""
    targets_text_es = " and ".join(_translate_device_to_spanish(d) for d in sorted(targets))
    targets_text_raw = " and ".join(sorted(targets))
    logger.warning("PROTECTION ACTIVATED%s. Forced operation: %s.", reason_text, targets_text_raw)

    notification_payload = _build_protection_notification_payload(reason, targets_text_es)
    pn.append(notification_payload)

    alert_enabled = sim.alert_enabled if sim else True
    if alert_enabled:
        eid = sim.edificio_id if sim else None
        persist_notification_in_django(
            "auto_protection", targets_text_es, "Critical",
            notification_payload["message"], edificio_id=eid
        )

    new_les = _send_protection_email(reason, targets_text_es, targets_text_raw, les)
    _set_attribute(sim, "last_email_sent_time", new_les)


def _get_expired_devices(protection_ends_dict: Dict[str, float]) -> List[str]:
    now = time.time()
    return [d for d, end in protection_ends_dict.items() if end and now >= end]


def _reset_device(device: str, sim: Any) -> None:
    from apps.sensors.simulation.controls import reset_critical_values

    try:
        reset_critical_values({device}, sim)
    except Exception:
        logger.exception("Error resetting critical values for %s", device)


def _clear_device_alerts(device: str, active_alerts_dict: Dict[str, str]) -> None:
    try:
        if device == "pump":
            for v in PUMP_VARS + ["rationing"]:
                active_alerts_dict.pop(v, None)
        elif device == "elevator":
            for v in ELEVATOR_VARS:
                active_alerts_dict.pop(v, None)
    except Exception:
        pass


def _notify_protection_ended(device: str, sim: Any, pn: list) -> None:
    device_es = "the water pump" if device == "pump" else "the elevator"
    alert_enabled = sim.alert_enabled if sim else True
    if alert_enabled:
        eid = sim.edificio_id if sim else None
        persist_notification_in_django(
            f"protection_{device}",
            None,
            "Info",
            f"Protection ended for {device_es}. Normal operation restored.",
            edificio_id=eid,
        )
    notification_payload = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "variable": f"protection_{device}",
        "value": None,
        "risk": "Info",
        "message": f"Protection ended for {device_es}. Normal operation restored.",
    }
    pn.append(notification_payload)


def update_protection_state(sim: Any = None) -> None:
    pe = _get_attribute(sim, "protection_ends")
    sd = _get_attribute(sim, "sensor_data")
    aa = _get_attribute(sim, "active_alerts")
    pn = _get_attribute(sim, "pending_notifications")

    expired = _get_expired_devices(pe)
    for device in expired:
        _reset_device(device, sim)
        _clear_device_alerts(device, aa)
        del pe[device]
        logger.info("Protection ended for %s. Device restored.", device)
        _notify_protection_ended(device, sim, pn)


def _determine_device_target(variable: str) -> Optional[str]:
    try:
        if variable in PUMP_VARS or variable == "rationing":
            return "pump"
        elif variable in ELEVATOR_VARS:
            return "elevator"
    except Exception:
        pass
    return None


def _build_alert_email_subject(variable: str, risk_level: str) -> str:
    var_display = _translate_variable_to_spanish(variable)
    return f"[Monitoring alert] Level {risk_level.lower()}: anomaly in {var_display.lower()}"


def _build_alert_email_body(
    variable: str, value: float, risk_level: str, recommended_action: str
) -> str:
    var_display = _translate_variable_to_spanish(variable)
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    unit = get_unit(variable)
    return (
        f"AUTOMATIC ANOMALY REPORT\n\n"
        f"A reading outside the recommended operational ranges has been detected "
        f"in the infrastructure monitoring sensors.\n\n"
        f"EVENT DETAILS:\n"
        f"{'':->44}\n"
        f"Date/Time:      {timestamp}\n"
        f"Parameter:      {var_display}\n"
        f"Reading:        {value} {unit}\n"
        f"Risk level:     {risk_level.lower()}\n\n"
        f"SUGGESTED CORRECTIVE MEASURES:\n"
        f"{'':->44}\n"
        f"Action:         {recommended_action}\n\n"
        f"This is an automatically generated contingency message. "
        f"Please proceed with the corresponding technical inspection."
    )


def _send_alert_email(
    variable: str,
    value: float,
    risk_level: str,
    recommended_action: str,
    last_email_time: float,
    sim: Any,
) -> float:
    new_les = last_email_time
    send_email = risk_level in ("Alto", "Critical")
    now = time.time()
    if send_email and now - last_email_time > COOLDOWN_SECONDS:
        new_les = now
        subject = _build_alert_email_subject(variable, risk_level)
        body = _build_alert_email_body(variable, value, risk_level, recommended_action)
        threading.Thread(
            target=send_email_alert, args=(risk_level, subject, body), daemon=True
        ).start()
    return new_les


def send_alert(
    variable: str,
    value: float,
    risk_level: str,
    recommended_action: str,
    sim: Any = None,
) -> None:
    aa = _get_attribute(sim, "active_alerts")
    les = _get_attribute(sim, "last_email_sent_time")

    alert_enabled = sim.alert_enabled if sim else True
    if not alert_enabled:
        logger.info("Alerts disabled by user")
        return

    if variable in aa and aa[variable] == risk_level:
        return
    aa[variable] = risk_level

    device_target = _determine_device_target(variable)

    if LOG_SIM:
        print(
            f"[SIM] {time.strftime('%H:%M:%S')} ALERT: {variable}={value} level={risk_level} mapped={device_target}"
        )

    if risk_level in ("Alto", "Critical"):
        if device_target:
            enter_protection_mode(
                f"alert {RISK_NAMES_ES.get(risk_level, risk_level.lower())} of {_translate_variable_to_spanish(variable).lower()}",
                targets={device_target},
                sim=sim,
            )
        else:
            logger.warning(
                "Critical alert for %s without device mapping; automatic protection will not be activated.",
                variable,
            )

    new_les = _send_alert_email(variable, value, risk_level, recommended_action, les, sim)
    _set_attribute(sim, "last_email_sent_time", new_les)

    pn = _get_attribute(sim, "pending_notifications")
    notification_payload = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "variable": variable,
        "value": value,
        "risk": risk_level,
        "message": recommended_action,
    }
    pn.append(notification_payload)

    eid = sim.edificio_id if sim else None
    persist_notification_in_django(variable, value, risk_level, recommended_action, edificio_id=eid)


def check_rationing(flow_rate: float, sim: Any = None) -> None:
    if flow_rate < RATIONING_THRESHOLD:
        action = get_professional_action("rationing", "Critical", flow_rate)
        send_alert("rationing", flow_rate, "Critical", action, sim=sim)
