from django.urls import path
from django.views.generic import RedirectView
from .views import (
    login_view,
    logout_view,
    menu_seleccion_view,
    usuario_view,
    lista_usuario_view,
    registro_beneficiario_view,
    editar_beneficiario_view,
    eliminar_beneficiario_view,
    descargar_pdf_view,
    registro_edificio_view,
    lista_edificios_view,
    editar_edificio_view,
    eliminar_edificio_view,
    notificaciones_view,
    toggle_alerts_session_view,
    limpiar_notificaciones_view,
    historial_view,
    historial_pdf_view,
    monitoreo_view,
    monitoreo_edificio_view,
    configuracion_view,
    seleccionar_usuario_view,
    seleccionar_edificio_view,
    completar_registro_view,
    simulador_status_view,
    simulador_start_view,
    simulador_stop_view,
    simulador_restart_view,
)
from .simulation_views import (
    sse_stream,
    api_status,
    api_edificios,
    api_usuarios_edificio,
    api_notifications,
    view_get_thresholds,
    view_update_thresholds,
    manual_update,
    view_clear_alerts,
    view_toggle_alerts,
    send_test_email,
    send_all_subscribers,
    sim_status,
    sim_pause,
    sim_reset,
    sim_inject_fault,
    sim_clear_fault,
    sim_set_speed,
    sim_toggle_pump,
    sim_toggle_elevator,
)

urlpatterns = [
    path("", RedirectView.as_view(url="/login/", permanent=False), name="home"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("menu_seleccion/", menu_seleccion_view, name="menu_seleccion"),
    path("usuario/", usuario_view, name="usuario"),
    path("lista_usuario/", lista_usuario_view, name="lista_usuario"),
    path(
        "registro_beneficiario/",
        registro_beneficiario_view,
        name="registro_beneficiario",
    ),
    path("registro_edificio/", registro_edificio_view, name="registro_edificio"),
    path("lista_edificios/", lista_edificios_view, name="lista_edificios"),
    path(
        "editar_edificio/<int:edificio_id>/",
        editar_edificio_view,
        name="editar_edificio",
    ),
    path(
        "eliminar_edificio/<int:edificio_id>/",
        eliminar_edificio_view,
        name="eliminar_edificio",
    ),
    path(
        "editar_beneficiario/<int:beneficiario_id>/",
        editar_beneficiario_view,
        name="editar_beneficiario",
    ),
    path(
        "eliminar_beneficiario/<int:beneficiario_id>/",
        eliminar_beneficiario_view,
        name="eliminar_beneficiario",
    ),
    path("descargar_pdf/", descargar_pdf_view, name="descargar_pdf"),
    path("notificaciones/", notificaciones_view, name="notificaciones"),
    path("historial/", historial_view, name="historial"),
    path("historial/pdf/", historial_pdf_view, name="historial_pdf"),
    path(
        "notificaciones/toggle_alerts/",
        toggle_alerts_session_view,
        name="toggle_alerts_session",
    ),
    path(
        "notificaciones/limpiar/",
        limpiar_notificaciones_view,
        name="limpiar_notificaciones",
    ),
    path("monitoreo/", monitoreo_view, name="monitoreo"),
    path(
        "monitoreo/edificio/<int:edificio_id>/",
        monitoreo_edificio_view,
        name="monitoreo_edificio",
    ),
    path("configuracion/", configuracion_view, name="configuracion"),
    path("completar_registro/", completar_registro_view, name="completar_registro"),
    path(
        "seleccionar/usuario/<str:accion>/",
        seleccionar_usuario_view,
        name="seleccionar_usuario",
    ),
    path(
        "seleccionar/edificio/<str:accion>/",
        seleccionar_edificio_view,
        name="seleccionar_edificio",
    ),
    path(
        "monitoreo/simulador/status/",
        simulador_status_view,
        name="simulador_status",
    ),
    path(
        "monitoreo/simulador/start/",
        simulador_start_view,
        name="simulador_start",
    ),
    path(
        "monitoreo/simulador/stop/",
        simulador_stop_view,
        name="simulador_stop",
    ),
    path(
        "monitoreo/simulador/restart/",
        simulador_restart_view,
        name="simulador_restart",
    ),
    # ─── SIMULACIÓN API (reemplaza routes.py Flask) ─────
    path("sse/<int:edificio_id>/", sse_stream, name="sse_stream"),
    path("api/status/", api_status, name="api_status"),
    path("api/edificios/", api_edificios, name="api_edificios"),
    path(
        "api/usuarios_edificio/<int:edificio_id>/",
        api_usuarios_edificio,
        name="api_usuarios_edificio",
    ),
    path("api/notifications/", api_notifications, name="api_notifications"),
    path("api/thresholds/", view_get_thresholds, name="api_thresholds"),
    path("api/thresholds/update/", view_update_thresholds, name="api_thresholds_update"),
    path("api/manual-update/", manual_update, name="manual_update"),
    path("api/clear-alerts/", view_clear_alerts, name="api_clear_alerts"),
    path("api/toggle-alerts/", view_toggle_alerts, name="api_toggle_alerts"),
    path("api/send-test-email/", send_test_email, name="api_send_test_email"),
    path(
        "api/send-all-subscribers/",
        send_all_subscribers,
        name="api_send_all_subscribers",
    ),
    path(
        "api/sim/<int:edificio_id>/status/",
        sim_status,
        name="sim_status_api",
    ),
    path(
        "api/sim/<int:edificio_id>/pause/",
        sim_pause,
        name="sim_pause_api",
    ),
    path(
        "api/sim/<int:edificio_id>/reset/",
        sim_reset,
        name="sim_reset_api",
    ),
    path(
        "api/sim/<int:edificio_id>/inject-fault/",
        sim_inject_fault,
        name="sim_inject_fault_api",
    ),
    path(
        "api/sim/<int:edificio_id>/clear-fault/",
        sim_clear_fault,
        name="sim_clear_fault_api",
    ),
    path(
        "api/sim/<int:edificio_id>/set-speed/",
        sim_set_speed,
        name="sim_set_speed_api",
    ),
    path(
        "api/sim/<int:edificio_id>/toggle-pump/",
        sim_toggle_pump,
        name="sim_toggle_pump_api",
    ),
    path(
        "api/sim/<int:edificio_id>/toggle-elevator/",
        sim_toggle_elevator,
        name="sim_toggle_elevator_api",
    ),
]
