from django.urls import path
from django.views.generic import RedirectView
from .views import (
    login_view,
    logout_view,
    menu_seleccion_view,
    usuario_view,
    lista_usuario_view,
    registro_beneficiario_view,
    editar_beneficiario_view,
    eliminar_beneficiario_view,
    descargar_pdf_view,
    registro_edificio_view,
    lista_edificios_view,
    editar_edificio_view,
    eliminar_edificio_view,
    notificaciones_view,
    limpiar_notificaciones_view,
    monitoreo_view,
    monitoreo_edificio_view,
    configuracion_view,
    seleccionar_usuario_view,
    seleccionar_edificio_view,
    completar_registro_view,
    simulador_status_view,
    simulador_start_view,
    simulador_stop_view,
    simulador_restart_view,
)

urlpatterns = [
    path("", RedirectView.as_view(url="/login/", permanent=False), name="home"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("menu_seleccion/", menu_seleccion_view, name="menu_seleccion"),
    path("usuario/", usuario_view, name="usuario"),
    path("lista_usuario/", lista_usuario_view, name="lista_usuario"),
    path(
        "registro_beneficiario/",
        registro_beneficiario_view,
        name="registro_beneficiario",
    ),
    path("registro_edificio/", registro_edificio_view, name="registro_edificio"),
    path("lista_edificios/", lista_edificios_view, name="lista_edificios"),
    path(
        "editar_edificio/<int:edificio_id>/",
        editar_edificio_view,
        name="editar_edificio",
    ),
    path(
        "eliminar_edificio/<int:edificio_id>/",
        eliminar_edificio_view,
        name="eliminar_edificio",
    ),
    path(
        "editar_beneficiario/<int:beneficiario_id>/",
        editar_beneficiario_view,
        name="editar_beneficiario",
    ),
    path(
        "eliminar_beneficiario/<int:beneficiario_id>/",
        eliminar_beneficiario_view,
        name="eliminar_beneficiario",
    ),
    path("descargar_pdf/", descargar_pdf_view, name="descargar_pdf"),
    path("notificaciones/", notificaciones_view, name="notificaciones"),
    path(
        "notificaciones/limpiar/",
        limpiar_notificaciones_view,
        name="limpiar_notificaciones",
    ),
    path("monitoreo/", monitoreo_view, name="monitoreo"),
    path(
        "monitoreo/edificio/<int:edificio_id>/",
        monitoreo_edificio_view,
        name="monitoreo_edificio",
    ),
    path("configuracion/", configuracion_view, name="configuracion"),
    path("completar_registro/", completar_registro_view, name="completar_registro"),
    path(
        "seleccionar/usuario/<str:accion>/",
        seleccionar_usuario_view,
        name="seleccionar_usuario",
    ),
    path(
        "seleccionar/edificio/<str:accion>/",
        seleccionar_edificio_view,
        name="seleccionar_edificio",
    ),
    path(
        "monitoreo/simulador/status/",
        simulador_status_view,
        name="simulador_status",
    ),
    path(
        "monitoreo/simulador/start/",
        simulador_start_view,
        name="simulador_start",
    ),
    path(
        "monitoreo/simulador/stop/",
        simulador_stop_view,
        name="simulador_stop",
    ),
    path(
        "monitoreo/simulador/restart/",
        simulador_restart_view,
        name="simulador_restart",
    ),
]
